FROM ruby:2.6.3
RUN apt-get update -qq && apt-get install -y nodejs libc-ares2 libnode64 libuv1 libpq-dev
RUN mkdir /blog
WORKDIR /blog
COPY . /blog
RUN bundle install
CMD ["rails", "server", "-b", "0.0.0.0"]
