version: '3'
services:
  db:
    image: postgres
  web:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/home/hosting/blog
    ports:
      - "3001:3000"
    depends_on:
      - db